export const FETCH_EXPENSE_START = 'FETCH_EXPENSE_START';
export const FETCH_EXPENSE_SUCCEEDED = 'FETCH_EXPENSE_SUCCEEDED';
export const FETCH_EXPENSE_FAILED = 'FETCH_EXPENSE_FAILED';

export const ADD_EXPENSE_START = 'ADD_EXPENSE_START';
export const ADD_EXPENSE_SUCCEEDED = 'ADD_EXPENSE_SUCCEEDED';
export const ADD_EXPENSE_FAILED = 'ADD_EXPENSE_FAILED';

